name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

env:
  plugin_name: vk-add-fonts-for-block-editor

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build and zip
        run: npm run zip  # ZIPファイルを生成するコマンド

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHubトークンを使用
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}  # タグ名のみ
          draft: false
          prerelease: false
          files: |
            dist/vk-add-fonts-for-block-editor.zip  # 生成されたZIPファイルのパス

      - name: Upload Release Asset
        if: steps.create_release.outcome == 'success'
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/vk-add-fonts-for-block-editor.zip  # 元のZIPファイルのパス
          asset_name: vk-add-fonts-for-block-editor.zip  # 元のZIPファイル名
          asset_content_type: application/zip